# Generated by Django 4.1.5 on 2023-01-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Stock', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Image', models.CharField(max_length=8000)),
            ],
        ),
    ]
